#!/bin/bash
echo '载入配置文件...'
. config.ini

apt-get update

apt-get -y install gcc python3-setuptools python3-pip python3.4-dev nginx language-pack-zh-hans

if [ ! $add_apt == '' ];then
    apt-get -y install $add_apt
fi 

pip3 install uwsgi virtualenv 

if [ ! $add_pip == '' ];then
    pip3 install $add_pip
fi

if [ ! -d "/etc/uwsgi/sites-enabled" ]; then
    mkdir -p /etc/uwsgi/sites-enabled
fi

if [ ! -d "/var/log/uwsgi" ]; then
    mkdir /var/log/uwsgi
fi

if [ ! -f "/etc/init/uwsgi.conf" ]; then
    cp uwsgi.conf /etc/init/
fi


read -p "reboot now ? [y/n]" res 

if [ $res == 'y' ] || [ $res == 'Y' ]; then
    reboot
fi
